# Generated by Django 4.2.30 on 2026-05-27 16:09

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('approve', 'Approved'), ('reject', 'Rejected')], max_length=20)),
                ('comments', models.TextField(blank=True, default='', help_text="Reviewer's comments explaining the decision")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('create', 'Created'), ('edit', 'Edited'), ('status_change', 'Status Changed'), ('approve', 'Approved'), ('reject', 'Rejected'), ('lock', 'Locked')], max_length=20)),
                ('field_name', models.CharField(blank=True, help_text='Which field was changed (null for non-edit actions)', max_length=100, null=True)),
                ('old_value', models.TextField(blank=True, help_text='Previous value before the change', null=True)),
                ('new_value', models.TextField(blank=True, help_text='New value after the change', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Human-readable name for this data source', max_length=255)),
                ('source_type', models.CharField(choices=[('sap_fuel', 'SAP Fuel & Procurement'), ('electricity', 'Electricity Bills'), ('travel', 'Corporate Travel')], help_text='Determines which parser is used for ingestion', max_length=50)),
                ('header_mappings', models.JSONField(blank=True, help_text='Custom column name mappings (JSON object). Keys are expected field names, values are actual column headers.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NormalizedRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_type', models.CharField(help_text='Denormalized from DataSource for query performance', max_length=50)),
                ('scope', models.CharField(choices=[('scope_1', 'Scope 1 - Direct Emissions'), ('scope_2', 'Scope 2 - Indirect (Energy)'), ('scope_3', 'Scope 3 - Indirect (Value Chain)')], max_length=20)),
                ('category', models.CharField(help_text="E.g., 'Stationary Combustion', 'Purchased Electricity', 'Business Travel'", max_length=100)),
                ('record_date', models.DateField(help_text='The date this emission event occurred')),
                ('original_unit', models.CharField(max_length=50)),
                ('original_value', models.DecimalField(decimal_places=6, max_digits=18)),
                ('normalized_unit', models.CharField(max_length=50)),
                ('normalized_value', models.DecimalField(decimal_places=6, max_digits=18)),
                ('emissions_kg_co2e', models.DecimalField(decimal_places=6, help_text='Calculated CO2-equivalent emissions in kilograms', max_digits=18)),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('parsed', 'Parsed'), ('failed', 'Failed'), ('suspicious', 'Suspicious'), ('approved', 'Approved'), ('locked', 'Locked')], default='uploaded', max_length=20)),
                ('validation_errors', models.JSONField(blank=True, default=list, help_text='List of validation error dicts: [{field, rule, message, severity}]')),
                ('suspicious_flag', models.BooleanField(default=False, help_text='Whether anomaly detection flagged this record')),
                ('suspicious_reason', models.TextField(blank=True, help_text='Explanation of why this record was flagged', null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RawRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('row_number', models.IntegerField(help_text='1-indexed row number from the original file (excluding header)')),
                ('original_data', models.JSONField(help_text='Complete original row data as key-value pairs')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['batch', 'row_number'],
            },
        ),
        migrations.CreateModel(
            name='UploadBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_name', models.CharField(help_text='Original filename as uploaded by user', max_length=500)),
                ('file', models.FileField(help_text='The actual uploaded file (CSV or Excel)', upload_to='uploads/%Y/%m/')),
                ('status', models.CharField(choices=[('uploading', 'Uploading'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='uploading', max_length=20)),
                ('total_rows', models.IntegerField(default=0, help_text='Total rows detected in file')),
                ('parsed_rows', models.IntegerField(default=0, help_text='Successfully parsed rows')),
                ('failed_rows', models.IntegerField(default=0, help_text='Rows that failed parsing/validation')),
                ('suspicious_rows', models.IntegerField(default=0, help_text='Rows flagged for review')),
                ('approved_rows', models.IntegerField(default=0, help_text='Rows approved by reviewer')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('data_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='ingestion.datasource')),
            ],
            options={
                'verbose_name_plural': 'Upload batches',
                'ordering': ['-created_at'],
            },
        ),
    ]
