# Generated by Django 4.2.30 on 2026-05-27 16:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ingestion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadbatch',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upload_batches', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='uploadbatch',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_batches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rawrecord',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_records', to='ingestion.uploadbatch'),
        ),
        migrations.AddField(
            model_name='normalizedrecord',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='normalizedrecord',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='normalized_records', to='ingestion.uploadbatch'),
        ),
        migrations.AddField(
            model_name='normalizedrecord',
            name='edited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edited_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='normalizedrecord',
            name='raw_record',
            field=models.OneToOneField(help_text='Link to the original unmodified data', on_delete=django.db.models.deletion.CASCADE, related_name='normalized', to='ingestion.rawrecord'),
        ),
        migrations.AddField(
            model_name='normalizedrecord',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='normalized_records', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='datasource',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_sources', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='changed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_actions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='normalized_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='ingestion.normalizedrecord'),
        ),
        migrations.AddField(
            model_name='approvalrecord',
            name='normalized_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_records', to='ingestion.normalizedrecord'),
        ),
        migrations.AddField(
            model_name='approvalrecord',
            name='reviewer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='rawrecord',
            unique_together={('batch', 'row_number')},
        ),
        migrations.AddIndex(
            model_name='normalizedrecord',
            index=models.Index(fields=['tenant', 'status'], name='ingestion_n_tenant__012efe_idx'),
        ),
        migrations.AddIndex(
            model_name='normalizedrecord',
            index=models.Index(fields=['tenant', 'scope'], name='ingestion_n_tenant__14f5fb_idx'),
        ),
        migrations.AddIndex(
            model_name='normalizedrecord',
            index=models.Index(fields=['tenant', 'source_type'], name='ingestion_n_tenant__3a03cc_idx'),
        ),
        migrations.AddIndex(
            model_name='normalizedrecord',
            index=models.Index(fields=['batch', 'status'], name='ingestion_n_batch_i_82adfe_idx'),
        ),
    ]
